using System.Text;
using CuriousInc.Source.Generators.Utilities.Models;
using Microsoft.CodeAnalysis;

namespace CuriousInc.Source.Generators.Utilities;

public class StronglyTypedIdGeneratorBase
{
    protected const string AttributeName = "StronglyTypedId";

    protected const string AttributeCode = $"""
                                            using System;
                                            namespace Headquarters.Utilities.SourceGenerators.Attributes;

                                            [AttributeUsage(AttributeTargets.Struct)]
                                            public sealed class StronglyTypedIdAttribute : Attribute;
                                            """;
    
    protected const string InterfaceName = "IStronglyTypedId";

    protected const string InterfaceCode = """
                                           using System;
                                           namespace Headquarters.Utilities.SourceGenerators.Attributes;
                                           
                                           public interface IStronglyTypedId<T> where T : struct
                                           {
                                                Guid Value { get; }
                                           }
                                           """;

    protected const string ICreatableInterface = $$"""

                                                   using System;
                                                   namespace Headquarters.Utilities.SourceGenerators.Attributes;
                                                   
                                                   public interface ICreatable<TSelf> where TSelf : ICreatable<TSelf>
                                                   {
                                                        abstract static TSelf Create();
                                                        abstract static TSelf Create(System.Guid value);
                                                        abstract static TSelf Create(string value);
                                                        abstract static TSelf Empty();
                                                   }
                                                   
                                                   """;

    protected static bool HasAttribute(INamedTypeSymbol symbol, string simpleName)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            var name = attr.AttributeClass?.Name;
            if (name is null) continue;

            // Matches StronglyTypedId or StronglyTypedIdAttribute
            if (name.Equals(simpleName, System.StringComparison.Ordinal) ||
                name.Equals(simpleName + "Attribute", System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    protected static IncrementalValuesProvider<GenerateSource> GeneratePartialType(IncrementalValuesProvider<SyntaxProviderCandidate> candidates)
    {
        return candidates.Select(static (t, _) =>
        {
            var (symbol, _, _) = t;
            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();
            
            var typeName = symbol.Name;
            
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("""
                          using System;
                          using System.Diagnostics;
                          using System.Diagnostics.CodeAnalysis;
                          using System.Text.Json;
                          using System.Text.Json.Serialization;
                          using Headquarters.Utilities.SourceGenerators.Attributes;
                          """);
            sb.AppendLine();
            
            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine($$"""
                          [JsonConverter(typeof({{typeName}}JsonConverter))]
                          [DebuggerDisplay("{Value}")]
                          public readonly partial record struct {{typeName}} : System.IParsable<{{typeName}}>, IStronglyTypedId<{{typeName}}>, ICreatable<{{typeName}}>
                          {
                                private {{typeName}}(System.Guid value) => Value = value;
                                
                                public System.Guid Value { get; }
                                
                                public readonly bool IsEmpty => Value == System.Guid.Empty;
                                
                                public static {{typeName}} Create() => new(System.Guid.CreateVersion7());
                                public static {{typeName}} Create(System.Guid value) => new(value);
                                public static {{typeName}} Create(string value) => new(System.Guid.Parse(value));
                                public static {{typeName}} Empty() => new(System.Guid.Empty);
                                public static implicit operator System.Guid({{typeName}} id) => id.Value;
                                public static implicit operator {{typeName}}(System.Guid value) => Create(value);
                                public static {{typeName}} Parse(string s, System.IFormatProvider? provider)
                                {
                                  return Create(s);
                                }
                              
                                public static bool TryParse([NotNullWhen(true)] string? s, System.IFormatProvider? provider, out {{typeName}} result)
                                {
                                  if (string.IsNullOrWhiteSpace(s))
                                  {
                                      result = Empty();
                                      return false;
                                  }
                                  
                                  result = Create(s);
                                  return true;
                                }
                                
                                public static bool operator ==({{typeName}} left, Guid right) => left.Value == right;
                                public static bool operator !=({{typeName}} left, Guid right) => left.Value != right;
                                public static bool operator ==(Guid left, {{typeName}} right) => left == right.Value;
                                public static bool operator !=(Guid left, {{typeName}} right) => left != right.Value;
                                
                                public override string ToString() => Value.ToString();
                          }
                          """);

            var source = sb.ToString();
            var hintName = $"{typeName}.g.cs";

            return new GenerateSource(hintName, source);
        });
    }

    protected static IncrementalValuesProvider<GenerateSource> GenerateJsonConverter(
        IncrementalValuesProvider<SyntaxProviderCandidate> candidates)
    {
        return candidates.Select(static (t, _) =>
        {
            var (symbol, _, _) = t;
            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();
            
            var typeName = symbol.Name;
            
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("""
                          using System;
                          using System.Diagnostics;
                          using System.Diagnostics.CodeAnalysis;
                          using System.Text.Json;
                          using System.Text.Json.Serialization;
                          """);
            sb.AppendLine();
            
            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine($$"""
                            public sealed class {{typeName}}JsonConverter : JsonConverter<{{typeName}}>
                            {
                                public override {{typeName}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                                {
                                
                                    if (reader.TokenType == JsonTokenType.Null)
                                    {
                                        return {{typeName}}.Empty();
                                    }

                                    if (reader.TokenType != JsonTokenType.String)
                                    {
                                        throw new JsonException($"Expected string token, but got {reader.TokenType}.");
                                    }
                                
                                    var value = reader.GetString();
                                    return string.IsNullOrWhiteSpace(value) ? {{typeName}}.Empty() : {{typeName}}.Create(value);
                                }
                                
                                public override void Write(Utf8JsonWriter writer, {{typeName}} value, JsonSerializerOptions options)
                                {
                                    if (value is { IsEmpty: true })
                                    {
                                        writer.WriteNullValue();
                                        return;
                                    }
                                    
                                    writer.WriteStringValue(value.Value.ToString());
                                }
                            }
                            """);
            
            var source = sb.ToString();
            var hintName = $"{typeName}.JsonConverter.g.cs";
            
            return new GenerateSource(hintName, source);
        });
    }
}