using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Curious.SourceGenerators;

[Generator]
public sealed class UnionGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Curious.SourceGenerator.Attributes.UnionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax rds &&
                    rds.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword),
                transform: static (ctx, _) => Transform(ctx))
            .Where(static t => t is not null);

        context.RegisterSourceOutput(targets, static (spc, target) => Execute(spc, target!));
    }

    private static UnionTarget? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        var syntax = (RecordDeclarationSyntax)ctx.TargetNode;
        var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var location = syntax.GetLocation();

        if (!symbol.IsReadOnly || !symbol.IsRecord || symbol.TypeKind != TypeKind.Struct)
            return Error(location, DiagnosticKind.NotReadonlyRecordStruct);

        if (!syntax.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return Error(location, DiagnosticKind.NotPartial);

        var typeParams = symbol.TypeParameters;
        if (typeParams.Length < 2)
            return Error(location, DiagnosticKind.TooFewTypeParameters);

        foreach (var tp in typeParams)
        {
            if (!tp.HasNotNullConstraint)
                return Error(location, DiagnosticKind.MissingNotNullConstraint);
        }

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        return new UnionTarget(
            location,
            ns,
            symbol.Name,
            typeParams.Select(tp => tp.Name).ToArray(),
            DiagnosticKind.None);
    }

    private static UnionTarget Error(Location location, DiagnosticKind kind) =>
        new UnionTarget(location, null, null, null, kind);

    private static void Execute(SourceProductionContext ctx, UnionTarget target)
    {
        if (target.Diagnostic != DiagnosticKind.None)
        {
            var descriptor = target.Diagnostic switch
            {
                DiagnosticKind.NotReadonlyRecordStruct => UnionDiagnostics.NotReadonlyRecordStruct,
                DiagnosticKind.NotPartial              => UnionDiagnostics.NotPartial,
                DiagnosticKind.TooFewTypeParameters    => UnionDiagnostics.TooFewTypeParameters,
                DiagnosticKind.MissingNotNullConstraint => UnionDiagnostics.MissingNotNullConstraint,
                _ => throw new InvalidOperationException("Unknown diagnostic kind.")
            };
            ctx.ReportDiagnostic(Diagnostic.Create(descriptor, target.Location));
            return;
        }

        int arity = target.TypeParamNames!.Length;
        ctx.AddSource($"{target.TypeName}.{arity}.g.cs", GenerateSource(target));
    }

    private static string GenerateSource(UnionTarget t)
    {
        var sb    = new StringBuilder();
        var names = t.TypeParamNames!;
        int n     = names.Length;
        string typeName  = t.TypeName!;
        string typeArgs  = Csv(names);
        string fullType  = $"{typeName}<{typeArgs}>";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        if (t.Namespace != null)
        {
            sb.AppendLine($"namespace {t.Namespace};");
            sb.AppendLine();
        }

        // --- type header -------------------------------------------------------
        sb.AppendLine($"readonly partial record struct {fullType}");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"    where {names[i]} : notnull");
        sb.AppendLine("{");

        // --- backing fields ----------------------------------------------------
        for (int i = 0; i < n; i++)
            sb.AppendLine($"    private readonly {names[i]}? _{Param(names[i])};");
        sb.AppendLine("    private readonly int _index;");
        sb.AppendLine();

        // --- private constructor -----------------------------------------------
        var ctorArgs = Csv(
            new[] { "int index" }
            .Concat(names.Select(name => $"{name}? {Param(name)}")));

        sb.AppendLine($"    private {typeName}({ctorArgs})");
        sb.AppendLine("    {");
        sb.AppendLine("        _index = index;");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"        _{Param(names[i])} = {Param(names[i])};");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- named factory methods: From{TypeParam} ----------------------------
        for (int i = 0; i < n; i++)
        {
            var callArgs = Csv(
                new[] { i.ToString() }
                .Concat(names.Select((_, j) => j == i ? Param(names[j]) : "default")));
            sb.AppendLine($"    public static {fullType} From{names[i]}({names[i]} {Param(names[i])}) => new({callArgs});");
        }
        sb.AppendLine();

        // --- overloaded From (convenience, may conflict when types overlap) ----
        for (int i = 0; i < n; i++)
            sb.AppendLine($"    public static {fullType} From({names[i]} {Param(names[i])}) => From{names[i]}({Param(names[i])});");
        sb.AppendLine();

        // --- implicit operators ------------------------------------------------
        for (int i = 0; i < n; i++)
            sb.AppendLine($"    public static implicit operator {fullType}({names[i]} {Param(names[i])}) => From{names[i]}({Param(names[i])});");
        sb.AppendLine();

        // --- Is{TypeParam} discriminator properties ----------------------------
        for (int i = 0; i < n; i++)
            sb.AppendLine($"    public bool Is{names[i]} => _index == {i};");
        sb.AppendLine();

        // --- TryGet{TypeParam} methods -----------------------------------------
        for (int i = 0; i < n; i++)
        {
            sb.AppendLine($"    public bool TryGet{names[i]}(out {names[i]}? value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        value = _{Param(names[i])};");
            sb.AppendLine($"        return _index == {i};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // --- Unwrap{TypeParam} -------------------------------------------------
        for (int i = 0; i < n; i++)
        {
            sb.AppendLine($"    public {names[i]} Unwrap{names[i]}() =>");
            sb.AppendLine($"        _index == {i}");
            sb.AppendLine($"            ? _{Param(names[i])}!");
            sb.AppendLine($"            : throw new InvalidOperationException($\"Cannot unwrap {names[i]}: union currently holds arm {{_index + 1}}.\");");
            sb.AppendLine();
        }

        // --- Match<TResult> (fold to a single type) ----------------------------
        var matchParams = Csv(names.Select(name => $"Func<{name}, TResult> {Param(name)}"));
        sb.AppendLine($"    public TResult Match<TResult>({matchParams}) =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"            {i} => {Param(names[i])}(_{Param(names[i])}!),");
        sb.AppendLine("            _ => throw new InvalidOperationException(\"Union is in an invalid state.\")");
        sb.AppendLine("        };");
        sb.AppendLine();

        // --- Switch (side effects, void) ---------------------------------------
        var switchParams = Csv(names.Select(name => $"Action<{name}> {Param(name)}"));
        sb.AppendLine($"    public void Switch({switchParams})");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (_index)");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"            case {i}: {Param(names[i])}(_{Param(names[i])}!); break;");
        sb.AppendLine("            default: throw new InvalidOperationException(\"Union is in an invalid state.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- Map{TypeParam}<TResult> (replace one arm, preserve others) --------
        for (int i = 0; i < n; i++)
        {
            string[] resultArgs = (string[])names.Clone();
            resultArgs[i] = "TResult";
            string resultType = $"{typeName}<{Csv(resultArgs)}>";

            sb.AppendLine($"    public {resultType} Map{names[i]}<TResult>(Func<{names[i]}, TResult> mapper)");
            sb.AppendLine("        where TResult : notnull =>");
            sb.AppendLine("        _index switch");
            sb.AppendLine("        {");
            for (int j = 0; j < n; j++)
            {
                string factory = j == i
                    ? $"{resultType}.From{names[j]}(mapper(_{Param(names[j])}!))"
                    : $"{resultType}.From{names[j]}(_{Param(names[j])}!)";
                sb.AppendLine($"            {j} => {factory},");
            }
            sb.AppendLine("            _ => throw new InvalidOperationException(\"Union is in an invalid state.\")");
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // --- Equals (explicit so record synthesis uses active-arm-only comparison)
        sb.AppendLine($"    public bool Equals({fullType} other) =>");
        sb.AppendLine("        _index == other._index &&");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"            {i} => EqualityComparer<{names[i]}>.Default.Equals(_{Param(names[i])}, other._{Param(names[i])}),");
        sb.AppendLine("            _ => false");
        sb.AppendLine("        };");
        sb.AppendLine();

        // --- GetHashCode -------------------------------------------------------
        sb.AppendLine("    public override int GetHashCode() =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"            {i} => HashCode.Combine({i}, _{Param(names[i])}),");
        sb.AppendLine("            _ => 0");
        sb.AppendLine("        };");
        sb.AppendLine();

        // --- ToString ----------------------------------------------------------
        sb.AppendLine("    public override string ToString() =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"            {i} => $\"{names[i]}({{_{Param(names[i])}}})\",");
        sb.AppendLine("            _ => \"Unknown\"");
        sb.AppendLine("        };");

        sb.AppendLine("}");
        return sb.ToString();
    }

    // Lowercases the first character to derive a parameter/field name.
    private static string Param(string typeParamName) =>
        char.ToLowerInvariant(typeParamName[0]) + typeParamName.Substring(1);

    private static string Csv(IEnumerable<string> items) => string.Join(", ", items);
}
