<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Curious.SourceGenerators.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Curious.SourceGenerators\Curious.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\..\Curious.SourceGenerator.Attributes\Curious.SourceGenerator.Attributes.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="DDD.UbiquitousLanguageRegistry.txt"/>
    </ItemGroup>

</Project>
