using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Curious.SourceGenerators.AspNet;

[Generator]
public sealed class UnionJsonConverterGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Curious.SourceGenerator.Attributes.UnionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax rds &&
                    rds.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword),
                transform: static (ctx, _) => Transform(ctx))
            .Where(static t => t is not null);

        context.RegisterSourceOutput(targets, static (spc, target) => Execute(spc, target!));
    }

    private static UnionJsonConverterTarget? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        var syntax = (RecordDeclarationSyntax)ctx.TargetNode;
        var symbol = (INamedTypeSymbol)ctx.TargetSymbol;

        if (!symbol.IsReadOnly || !symbol.IsRecord || symbol.TypeKind != TypeKind.Struct)
            return null;

        if (!syntax.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return null;

        var typeParams = symbol.TypeParameters;
        if (typeParams.Length < 2)
            return null;

        foreach (var tp in typeParams)
            if (!tp.HasNotNullConstraint)
                return null;

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        return new UnionJsonConverterTarget(ns, symbol.Name, typeParams.Select(tp => tp.Name).ToArray());
    }

    private static void Execute(SourceProductionContext ctx, UnionJsonConverterTarget target)
    {
        int arity = target.TypeParamNames.Length;
        ctx.AddSource($"{target.TypeName}.{arity}.JsonConverter.g.cs", GenerateSource(target));
    }

    private static string GenerateSource(UnionJsonConverterTarget t)
    {
        var sb       = new StringBuilder();
        var names    = t.TypeParamNames;
        int n        = names.Length;
        string typeName     = t.TypeName;
        string typeArgs     = Csv(names);
        string fullType     = $"{typeName}<{typeArgs}>";
        string openCommas   = new string(',', n - 1);
        string converterName = $"{typeName}JsonConverter";
        // Non-generic factory name must include the arity to avoid clashes when the
        // same type name exists at different arities (e.g. Union<T1,T2> vs Union<T1,T2,T3>).
        string factoryName   = $"{typeName}{n}JsonConverterFactory";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        if (t.Namespace != null)
        {
            sb.AppendLine($"namespace {t.Namespace};");
            sb.AppendLine();
        }

        // Attach [JsonConverter] to the partial struct so STJ picks it up automatically.
        sb.AppendLine($"[JsonConverter(typeof({factoryName}))]");
        sb.AppendLine($"readonly partial record struct {fullType}");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"    where {names[i]} : notnull");
        sb.AppendLine(";");
        sb.AppendLine();

        // ── Factory ────────────────────────────────────────────────────────────
        // Non-generic so it can be referenced by the [JsonConverter] attribute.
        // Uses MakeGenericType + Activator.CreateInstance, which requires dynamic
        // code — annotated accordingly for NativeAOT / trimming toolchains.
        sb.AppendLine($"public sealed class {factoryName} : global::System.Text.Json.Serialization.JsonConverterFactory");
        sb.AppendLine("{");
        sb.AppendLine("    public override bool CanConvert(global::System.Type typeToConvert) =>");
        sb.AppendLine("        typeToConvert.IsGenericType &&");
        sb.AppendLine($"        typeToConvert.GetGenericTypeDefinition() == typeof({typeName}<{openCommas}>);");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(");
        sb.AppendLine($"        \"Creating a {converterName}<> requires dynamic code at runtime.\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(");
        sb.AppendLine($"        \"Creating a {converterName}<> may require types that cannot be statically analyzed.\")]");
        sb.AppendLine("    public override global::System.Text.Json.Serialization.JsonConverter CreateConverter(");
        sb.AppendLine("        global::System.Type typeToConvert,");
        sb.AppendLine("        global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var args = typeToConvert.GetGenericArguments();");
        sb.AppendLine($"        return (global::System.Text.Json.Serialization.JsonConverter)");
        sb.AppendLine($"            global::System.Activator.CreateInstance(");
        sb.AppendLine($"                typeof({converterName}<{openCommas}>).MakeGenericType(args))!;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Typed converter ────────────────────────────────────────────────────
        sb.AppendLine($"public sealed class {converterName}<{typeArgs}> : global::System.Text.Json.Serialization.JsonConverter<{fullType}>");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"    where {names[i]} : notnull");
        sb.AppendLine("{");

        // Read ─────────────────────────────────────────────────────────────────
        sb.AppendLine($"    public override {fullType} Read(");
        sb.AppendLine("        ref global::System.Text.Json.Utf8JsonReader reader,");
        sb.AppendLine("        global::System.Type typeToConvert,");
        sb.AppendLine("        global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)");
        sb.AppendLine("            throw new global::System.Text.Json.JsonException(\"Expected start of JSON object for union.\");");
        sb.AppendLine();
        sb.AppendLine("        int? index = null;");
        sb.AppendLine("        global::System.Text.Json.JsonElement? bufferedValue = null;");
        sb.AppendLine();
        sb.AppendLine("        while (reader.Read())");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.TokenType == global::System.Text.Json.JsonTokenType.EndObject)");
        sb.AppendLine("                break;");
        sb.AppendLine();
        sb.AppendLine("            if (reader.TokenType != global::System.Text.Json.JsonTokenType.PropertyName)");
        sb.AppendLine("                throw new global::System.Text.Json.JsonException(\"Expected property name in union JSON.\");");
        sb.AppendLine();
        sb.AppendLine("            var prop = reader.GetString();");
        sb.AppendLine("            reader.Read();");
        sb.AppendLine();
        sb.AppendLine("            switch (prop)");
        sb.AppendLine("            {");
        sb.AppendLine("                case \"$index\":");
        sb.AppendLine("                    index = reader.GetInt32();");
        sb.AppendLine("                    break;");
        sb.AppendLine("                case \"value\":");
        sb.AppendLine("                    if (index.HasValue)");
        sb.AppendLine("                        return DeserializeArm(ref reader, index.Value, options);");
        sb.AppendLine("                    bufferedValue = global::System.Text.Json.JsonElement.ParseValue(ref reader);");
        sb.AppendLine("                    break;");
        sb.AppendLine("                default:");
        sb.AppendLine("                    reader.Skip();");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (index is null)");
        sb.AppendLine("            throw new global::System.Text.Json.JsonException(\"Union JSON is missing the '$index' property.\");");
        sb.AppendLine("        if (bufferedValue is null)");
        sb.AppendLine("            throw new global::System.Text.Json.JsonException(\"Union JSON is missing the 'value' property.\");");
        sb.AppendLine();
        sb.AppendLine("        return DeserializeBuffered(bufferedValue.Value, index.Value, options);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // DeserializeArm — $index arrived before value, reader is positioned on the value token.
        sb.AppendLine($"    private static {fullType} DeserializeArm(");
        sb.AppendLine("        ref global::System.Text.Json.Utf8JsonReader reader,");
        sb.AppendLine("        int index,");
        sb.AppendLine("        global::System.Text.Json.JsonSerializerOptions options) =>");
        sb.AppendLine("        index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"            {i} => {fullType}.From{names[i]}(global::System.Text.Json.JsonSerializer.Deserialize<{names[i]}>(ref reader, options)!),");
        sb.AppendLine("            _ => throw new global::System.Text.Json.JsonException($\"Unknown union arm index {{{nameof(index)}}}.\")");
        sb.AppendLine("        };");
        sb.AppendLine();

        // DeserializeBuffered — value arrived before $index, buffered as JsonElement.
        sb.AppendLine($"    private static {fullType} DeserializeBuffered(");
        sb.AppendLine("        global::System.Text.Json.JsonElement element,");
        sb.AppendLine("        int index,");
        sb.AppendLine("        global::System.Text.Json.JsonSerializerOptions options) =>");
        sb.AppendLine("        index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
            sb.AppendLine($"            {i} => {fullType}.From{names[i]}(element.Deserialize<{names[i]}>(options)!),");
        sb.AppendLine("            _ => throw new global::System.Text.Json.JsonException($\"Unknown union arm index {{{nameof(index)}}}.\")");
        sb.AppendLine("        };");
        sb.AppendLine();

        // Write ────────────────────────────────────────────────────────────────
        sb.AppendLine($"    public override void Write(");
        sb.AppendLine("        global::System.Text.Json.Utf8JsonWriter writer,");
        sb.AppendLine($"        {fullType} value,");
        sb.AppendLine("        global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteStartObject();");
        sb.AppendLine("        value.Switch(");
        for (int i = 0; i < n; i++)
        {
            string param  = Param(names[i]);
            string suffix = i < n - 1 ? "," : ");";
            sb.AppendLine($"            {param} =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                writer.WriteNumber(\"$index\", {i});");
            sb.AppendLine("                writer.WritePropertyName(\"value\");");
            sb.AppendLine($"                global::System.Text.Json.JsonSerializer.Serialize(writer, {param}, options);");
            sb.AppendLine($"            }}{suffix}");
        }
        sb.AppendLine("        writer.WriteEndObject();");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Param(string typeParamName) =>
        char.ToLowerInvariant(typeParamName[0]) + typeParamName.Substring(1);

    private static string Csv(IEnumerable<string> items) => string.Join(", ", items);
}
